# Generated by Django 6.0.3 on 2026-04-29 09:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_alter_taskerprofile_options_and_more"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetencyArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaskerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("document_review", "Document Review"),
                            ("interview_pending", "Interview Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("headline", models.CharField(blank=True, default="", max_length=200)),
                ("bio", models.TextField(blank=True, default="")),
                ("years_experience", models.PositiveIntegerField(default=0)),
                (
                    "education_level",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("portfolio_url", models.URLField(blank=True, default="")),
                ("trust_score", models.FloatField(default=0.0)),
                ("document_confidence", models.FloatField(default=0.0)),
                ("competency_confidence", models.FloatField(default=0.0)),
                ("interview_confidence", models.FloatField(default=0.0)),
                ("fraud_risk_score", models.FloatField(default=0.0)),
                ("manual_review_required", models.BooleanField(default=False)),
                ("human_override", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasker_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competency_areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applications",
                        to="trust.competencyarea",
                    ),
                ),
                (
                    "region_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasker_applications",
                        to="operations.region",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_tasker_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasker_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_application",
                        to="assignments.taskerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "selfie_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="trust/selfies/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "id_front_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="trust/ids/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "id_back_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="trust/ids/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp", "pdf"]
                            )
                        ],
                    ),
                ),
                ("face_match_score", models.FloatField(default=0.0)),
                ("liveness_score", models.FloatField(default=0.0)),
                ("document_match_score", models.FloatField(default=0.0)),
                ("authenticity_score", models.FloatField(default=0.0)),
                ("review_notes", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_verification",
                        to="trust.taskerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("writing", "Writing"),
                            ("behavioral", "Behavioral"),
                            ("blended", "Blended"),
                        ],
                        default="blended",
                        max_length=20,
                    ),
                ),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("transcript_text", models.TextField(blank=True, default="")),
                ("technical_score", models.FloatField(default=0.0)),
                ("writing_score", models.FloatField(default=0.0)),
                ("behavioral_score", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(default=0.0)),
                (
                    "recommendation",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("ranking_percentile", models.FloatField(default=0.0)),
                (
                    "interviewer_version",
                    models.CharField(blank=True, default="v1", max_length=60),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="trust.taskerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume / CV"),
                            ("certificate", "Certificate"),
                            ("credential", "Academic Credential"),
                            ("portfolio", "Portfolio Sample"),
                            ("government_id", "Government ID"),
                            ("selfie", "Selfie"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="trust/taskers/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "webp",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("authenticity_score", models.FloatField(default=0.0)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                (
                    "sha256_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("verified_by_ai", models.BooleanField(default=False)),
                ("needs_manual_review", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="trust.taskerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInterviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("evidence", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="trust.aiinterviewsession",
                    ),
                ),
                (
                    "competency_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_scores",
                        to="trust.competencyarea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("session", "competency_area")},
            },
        ),
    ]
