# Generated by Django 6.0.3 on 2026-04-28 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "churn_probability",
                    models.FloatField(
                        default=0.0, help_text="0-100 probability of churn"
                    ),
                ),
                (
                    "health_score",
                    models.IntegerField(default=50, help_text="0-100 account health"),
                ),
                ("engagement_level", models.CharField(default="medium", max_length=20)),
                ("predicted_usage_next_month", models.IntegerField(default=0)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_prediction",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("profile_update", "Profile Update"),
                            ("billing_view", "Billing View"),
                            ("pricing_view", "Pricing View"),
                            ("support_contact", "Support Contact"),
                            ("feature_use", "Feature Use"),
                        ],
                        max_length=50,
                    ),
                ),
                ("path", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="analytics_u_user_id_779c80_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="analytics_u_action_d695f0_idx",
                    ),
                ],
            },
        ),
    ]
