# Generated by Django 6.0.3 on 2026-04-30 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=255, unique=True)),
                (
                    "cache_type",
                    models.CharField(
                        choices=[("corpus", "Corpus"), ("author", "Author")],
                        max_length=20,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("marketplace", "Marketplace"),
                            ("assignments", "Assignments"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "source_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("sample_text_count", models.PositiveIntegerField(default=0)),
                ("source_window_days", models.PositiveIntegerField(default=30)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-refreshed_at"],
                "indexes": [
                    models.Index(
                        fields=["cache_type", "source_kind"],
                        name="analytics_p_cache_t_2a0164_idx",
                    ),
                    models.Index(
                        fields=["source_kind", "source_object_id"],
                        name="analytics_p_source__9bbf10_idx",
                    ),
                    models.Index(
                        fields=["author", "cache_type"],
                        name="analytics_p_author__8766cf_idx",
                    ),
                ],
            },
        ),
    ]
