# Generated by Django 6.0.3 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskerprofile",
            options={
                "ordering": ["-trust_score", "-quality_score", "-completed_assignments"]
            },
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="admin_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
