# Generated by Django 6.0.3 on 2026-04-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_taskerprofile_competency_areas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Verification Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "academic_field",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("medicine", "Medicine"),
                            ("technology", "Technology"),
                            ("architecture", "Architecture"),
                            ("law", "Law"),
                            ("business", "Business"),
                            ("sciences", "Sciences"),
                            ("humanities", "Humanities"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subfield", models.CharField(blank=True, default="", max_length=255)),
                ("submission_type", models.CharField(max_length=50)),
                (
                    "overall_score",
                    models.FloatField(default=0.0, help_text="Overall score 0-100"),
                ),
                ("passed", models.BooleanField(default=False)),
                ("verification_results", models.JSONField(blank=True, default=dict)),
                ("issues_found", models.JSONField(blank=True, default=list)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="assignments.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentVerificationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_type", models.CharField(max_length=50)),
                (
                    "score",
                    models.FloatField(help_text="Score for this specific check 0-100"),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("passed", models.BooleanField(default=False)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="assignments.assignmentverification",
                    ),
                ),
            ],
            options={
                "ordering": ["check_type"],
            },
        ),
        migrations.AddIndex(
            model_name="assignmentverification",
            index=models.Index(
                fields=["status", "created_at"], name="assignments_status_f779ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentverification",
            index=models.Index(
                fields=["academic_field", "passed"],
                name="assignments_academi_5662b6_idx",
            ),
        ),
    ]
