# Generated by Django 6.0.3 on 2026-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_init_email_customer_init_email_confirmed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="stripe_id",
            new_name="paystack_id",
        ),
    ]
