# Generated by Django 6.0.3 on 2026-04-30 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard Access"),
                            ("marketplace", "Marketplace Access"),
                            ("assignments", "Assignment Management"),
                            ("chat", "Chat & Communication"),
                            ("verification", "Assignment Verification"),
                            ("moderation", "Moderation Tools"),
                            ("admin", "Admin Tools"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermissionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("tasker", "Tasker"),
                            ("manager", "Manager/Moderator"),
                            ("admin", "Administrator"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        related_name="role_templates", to="platform_auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Role Permission Templates",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("tasker", "Tasker"),
                            ("manager", "Manager/Moderator"),
                            ("admin", "Administrator"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platform_auth.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="platform_auth.userrole",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "permission")},
            },
        ),
    ]
