# Generated by Django 6.0.3 on 2026-04-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0003_taskerprofile_competency_areas_and_more"),
        ("marketplace", "0001_initial"),
        ("operations", "0001_initial"),
        ("trust", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskorder",
            name="competency_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="trust.competencyarea",
            ),
        ),
        migrations.AddField(
            model_name="taskorder",
            name="region_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="operations.region",
            ),
        ),
        migrations.AddField(
            model_name="taskorder",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasknotification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskmatchsuggestion",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_suggestions",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskconversationmessage",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskauditevent",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskpayment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskrating",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskrating",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="taskrating",
            name="tasker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="assignments.taskerprofile",
            ),
        ),
        migrations.AddField(
            model_name="taskrevisionrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskstatusevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_status_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskstatusevent",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="tasksubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasksubmission",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="marketplace.taskorder",
            ),
        ),
        migrations.AddField(
            model_name="tasksubmission",
            name="tasker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.taskerprofile",
            ),
        ),
        migrations.AddField(
            model_name="taskrevisionrequest",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revision_requests",
                to="marketplace.tasksubmission",
            ),
        ),
        migrations.AddIndex(
            model_name="taskorder",
            index=models.Index(
                fields=["status", "created_at"], name="marketplace_status_ac3a93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskorder",
            index=models.Index(
                fields=["student", "status"], name="marketplace_student_88b2d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskorder",
            index=models.Index(
                fields=["assigned_tasker", "status"],
                name="marketplace_assigne_382137_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskorder",
            index=models.Index(
                fields=["deadline", "status"], name="marketplace_deadlin_05b66b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskmatchsuggestion",
            unique_together={("task", "tasker")},
        ),
        migrations.AlterUniqueTogether(
            name="taskrating",
            unique_together={("task", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="tasksubmission",
            unique_together={("task", "tasker", "version")},
        ),
    ]
