# Generated by Django 6.0.3 on 2026-05-01 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_assignment_verification_rubric"),
        ("marketplace", "0004_taskconversationreadstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpayment",
            name="payment_kind",
            field=models.CharField(
                choices=[("task", "Task"), ("premium_session", "Premium Session")],
                default="task",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TaskPremiumSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching"),
                            ("revision", "Revision"),
                            ("exam_prep", "Exam Prep"),
                        ],
                        default="teaching",
                        max_length=32,
                    ),
                ),
                ("topic", models.CharField(max_length=180)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "extra_fee_cents",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("paid", "Paid"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=24,
                    ),
                ),
                ("student_notes", models.TextField(blank=True, default="")),
                ("tasker_notes", models.TextField(blank=True, default="")),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="premium_session",
                        to="marketplace.taskpayment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_session_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_sessions",
                        to="marketplace.taskorder",
                    ),
                ),
                (
                    "tasker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_session_requests",
                        to="assignments.taskerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
