# Generated by Django 6.0.3 on 2026-04-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_alter_taskerprofile_options_and_more"),
        ("operations", "0001_initial"),
        ("trust", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskerprofile",
            name="competency_areas",
            field=models.ManyToManyField(
                blank=True, related_name="taskers", to="trust.competencyarea"
            ),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="competency_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("flagged", "Flagged"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="current_workload_hours",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="fraud_risk_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="home_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taskers",
                to="operations.region",
            ),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="interview_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("scheduled", "Scheduled"),
                    ("passed", "Passed"),
                    ("under_review", "Under Review"),
                    ("failed", "Failed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="is_accepting_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="last_ai_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="last_assessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="quality_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="reliability_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="revision_frequency",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="taskerprofile",
            name="trust_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="tasker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to="assignments.taskerprofile",
            ),
        ),
    ]
