# Generated by Django 6.0.3 on 2026-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0022_usersubscription_timestamp_usersubscription_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="stripe_id",
            new_name="paystack_id",
        ),
        migrations.RenameField(
            model_name="subscriptionprice",
            old_name="stripe_id",
            new_name="paystack_id",
        ),
        migrations.RenameField(
            model_name="usersubscription",
            old_name="stripe_id",
            new_name="paystack_id",
        ),
    ]
