# Generated by Django 6.0.3 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0023_rename_stripe_id_subscription_paystack_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="feature_codes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
